version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./data/db:/data/db
    networks:
      - app-network
    restart: always

  php-fpm-nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8053:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge